/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CollaboratorUpdateManyWithoutProjectsInput } from "./CollaboratorUpdateManyWithoutProjectsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ImageUpdateManyWithoutProjectsInput } from "./ImageUpdateManyWithoutProjectsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CollaboratorUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => CollaboratorUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => CollaboratorUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  collaborators?: CollaboratorUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ImageUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ImageUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  images?: ImageUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tool?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ProjectUpdateInput as ProjectUpdateInput };
