/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CollaboratorCreateNestedManyWithoutProjectsInput } from "./CollaboratorCreateNestedManyWithoutProjectsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ImageCreateNestedManyWithoutProjectsInput } from "./ImageCreateNestedManyWithoutProjectsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: () => CollaboratorCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => CollaboratorCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => CollaboratorCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  collaborators?: CollaboratorCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => ImageCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => ImageCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  images?: ImageCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tool?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { ProjectCreateInput as ProjectCreateInput };
