/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Aimodel } from "./Aimodel";
import { AimodelCountArgs } from "./AimodelCountArgs";
import { AimodelFindManyArgs } from "./AimodelFindManyArgs";
import { AimodelFindUniqueArgs } from "./AimodelFindUniqueArgs";
import { CreateAimodelArgs } from "./CreateAimodelArgs";
import { UpdateAimodelArgs } from "./UpdateAimodelArgs";
import { DeleteAimodelArgs } from "./DeleteAimodelArgs";
import { AnnotationFindManyArgs } from "../../annotation/base/AnnotationFindManyArgs";
import { Annotation } from "../../annotation/base/Annotation";
import { AimodelService } from "../aimodel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Aimodel)
export class AimodelResolverBase {
  constructor(
    protected readonly service: AimodelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "any",
  })
  async _aimodelsMeta(
    @graphql.Args() args: AimodelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Aimodel])
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "any",
  })
  async aimodels(
    @graphql.Args() args: AimodelFindManyArgs
  ): Promise<Aimodel[]> {
    return this.service.aimodels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Aimodel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "own",
  })
  async aimodel(
    @graphql.Args() args: AimodelFindUniqueArgs
  ): Promise<Aimodel | null> {
    const result = await this.service.aimodel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Aimodel)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "create",
    possession: "any",
  })
  async createAimodel(
    @graphql.Args() args: CreateAimodelArgs
  ): Promise<Aimodel> {
    return await this.service.createAimodel({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Aimodel)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "update",
    possession: "any",
  })
  async updateAimodel(
    @graphql.Args() args: UpdateAimodelArgs
  ): Promise<Aimodel | null> {
    try {
      return await this.service.updateAimodel({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Aimodel)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "delete",
    possession: "any",
  })
  async deleteAimodel(
    @graphql.Args() args: DeleteAimodelArgs
  ): Promise<Aimodel | null> {
    try {
      return await this.service.deleteAimodel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Annotation], { name: "annotations" })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "any",
  })
  async findAnnotations(
    @graphql.Parent() parent: Aimodel,
    @graphql.Args() args: AnnotationFindManyArgs
  ): Promise<Annotation[]> {
    const results = await this.service.findAnnotations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
