/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AimodelService } from "../aimodel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AimodelCreateInput } from "./AimodelCreateInput";
import { Aimodel } from "./Aimodel";
import { AimodelFindManyArgs } from "./AimodelFindManyArgs";
import { AimodelWhereUniqueInput } from "./AimodelWhereUniqueInput";
import { AimodelUpdateInput } from "./AimodelUpdateInput";
import { AnnotationFindManyArgs } from "../../annotation/base/AnnotationFindManyArgs";
import { Annotation } from "../../annotation/base/Annotation";
import { AnnotationWhereUniqueInput } from "../../annotation/base/AnnotationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AimodelControllerBase {
  constructor(
    protected readonly service: AimodelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Aimodel })
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAimodel(
    @common.Body() data: AimodelCreateInput
  ): Promise<Aimodel> {
    return await this.service.createAimodel({
      data: data,
      select: {
        createdAt: true,
        id: true,
        modelType: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Aimodel] })
  @ApiNestedQuery(AimodelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aimodels(@common.Req() request: Request): Promise<Aimodel[]> {
    const args = plainToClass(AimodelFindManyArgs, request.query);
    return this.service.aimodels({
      ...args,
      select: {
        createdAt: true,
        id: true,
        modelType: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Aimodel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aimodel(
    @common.Param() params: AimodelWhereUniqueInput
  ): Promise<Aimodel | null> {
    const result = await this.service.aimodel({
      where: params,
      select: {
        createdAt: true,
        id: true,
        modelType: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Aimodel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAimodel(
    @common.Param() params: AimodelWhereUniqueInput,
    @common.Body() data: AimodelUpdateInput
  ): Promise<Aimodel | null> {
    try {
      return await this.service.updateAimodel({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          modelType: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Aimodel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAimodel(
    @common.Param() params: AimodelWhereUniqueInput
  ): Promise<Aimodel | null> {
    try {
      return await this.service.deleteAimodel({
        where: params,
        select: {
          createdAt: true,
          id: true,
          modelType: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/annotations")
  @ApiNestedQuery(AnnotationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "any",
  })
  async findAnnotations(
    @common.Req() request: Request,
    @common.Param() params: AimodelWhereUniqueInput
  ): Promise<Annotation[]> {
    const query = plainToClass(AnnotationFindManyArgs, request.query);
    const results = await this.service.findAnnotations(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "update",
    possession: "any",
  })
  async connectAnnotations(
    @common.Param() params: AimodelWhereUniqueInput,
    @common.Body() body: AnnotationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      annotations: {
        connect: body,
      },
    };
    await this.service.updateAimodel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "update",
    possession: "any",
  })
  async updateAnnotations(
    @common.Param() params: AimodelWhereUniqueInput,
    @common.Body() body: AnnotationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      annotations: {
        set: body,
      },
    };
    await this.service.updateAimodel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/annotations")
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "update",
    possession: "any",
  })
  async disconnectAnnotations(
    @common.Param() params: AimodelWhereUniqueInput,
    @common.Body() body: AnnotationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      annotations: {
        disconnect: body,
      },
    };
    await this.service.updateAimodel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
