/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AnnotationService } from "../annotation.service";
import { AnnotationCreateInput } from "./AnnotationCreateInput";
import { Annotation } from "./Annotation";
import { AnnotationFindManyArgs } from "./AnnotationFindManyArgs";
import { AnnotationWhereUniqueInput } from "./AnnotationWhereUniqueInput";
import { AnnotationUpdateInput } from "./AnnotationUpdateInput";
import { AimodelFindManyArgs } from "../../aimodel/base/AimodelFindManyArgs";
import { Aimodel } from "../../aimodel/base/Aimodel";
import { AimodelWhereUniqueInput } from "../../aimodel/base/AimodelWhereUniqueInput";

export class AnnotationControllerBase {
  constructor(protected readonly service: AnnotationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Annotation })
  async createAnnotation(
    @common.Body() data: AnnotationCreateInput
  ): Promise<Annotation> {
    return await this.service.createAnnotation({
      data: {
        ...data,

        image: {
          connect: data.image,
        },

        validatedBy: data.validatedBy
          ? {
              connect: data.validatedBy,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Annotation] })
  @ApiNestedQuery(AnnotationFindManyArgs)
  async annotations(@common.Req() request: Request): Promise<Annotation[]> {
    const args = plainToClass(AnnotationFindManyArgs, request.query);
    return this.service.annotations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async annotation(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    const result = await this.service.annotation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAnnotation(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() data: AnnotationUpdateInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.updateAnnotation({
        where: params,
        data: {
          ...data,

          image: {
            connect: data.image,
          },

          validatedBy: data.validatedBy
            ? {
                connect: data.validatedBy,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          result: true,
          updatedAt: true,
          url: true,

          validatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAnnotation(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.deleteAnnotation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          result: true,
          updatedAt: true,
          url: true,

          validatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/aiModel")
  @ApiNestedQuery(AimodelFindManyArgs)
  async findAiModel(
    @common.Req() request: Request,
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Aimodel[]> {
    const query = plainToClass(AimodelFindManyArgs, request.query);
    const results = await this.service.findAiModel(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        modelType: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/aiModel")
  async connectAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        connect: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/aiModel")
  async updateAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        set: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/aiModel")
  async disconnectAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        disconnect: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
