/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AnnotationService } from "../annotation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AnnotationCreateInput } from "./AnnotationCreateInput";
import { Annotation } from "./Annotation";
import { AnnotationFindManyArgs } from "./AnnotationFindManyArgs";
import { AnnotationWhereUniqueInput } from "./AnnotationWhereUniqueInput";
import { AnnotationUpdateInput } from "./AnnotationUpdateInput";
import { AimodelFindManyArgs } from "../../aimodel/base/AimodelFindManyArgs";
import { Aimodel } from "../../aimodel/base/Aimodel";
import { AimodelWhereUniqueInput } from "../../aimodel/base/AimodelWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AnnotationControllerBase {
  constructor(
    protected readonly service: AnnotationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Annotation })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAnnotation(
    @common.Body() data: AnnotationCreateInput
  ): Promise<Annotation> {
    return await this.service.createAnnotation({
      data: {
        ...data,

        image: {
          connect: data.image,
        },

        validatedBy: data.validatedBy
          ? {
              connect: data.validatedBy,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Annotation] })
  @ApiNestedQuery(AnnotationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async annotations(@common.Req() request: Request): Promise<Annotation[]> {
    const args = plainToClass(AnnotationFindManyArgs, request.query);
    return this.service.annotations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async annotation(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    const result = await this.service.annotation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        result: true,
        updatedAt: true,
        url: true,

        validatedBy: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAnnotation(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() data: AnnotationUpdateInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.updateAnnotation({
        where: params,
        data: {
          ...data,

          image: {
            connect: data.image,
          },

          validatedBy: data.validatedBy
            ? {
                connect: data.validatedBy,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          result: true,
          updatedAt: true,
          url: true,

          validatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Annotation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAnnotation(
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Annotation | null> {
    try {
      return await this.service.deleteAnnotation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          result: true,
          updatedAt: true,
          url: true,

          validatedBy: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/aiModel")
  @ApiNestedQuery(AimodelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Aimodel",
    action: "read",
    possession: "any",
  })
  async findAiModel(
    @common.Req() request: Request,
    @common.Param() params: AnnotationWhereUniqueInput
  ): Promise<Aimodel[]> {
    const query = plainToClass(AimodelFindManyArgs, request.query);
    const results = await this.service.findAiModel(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        modelType: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/aiModel")
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "update",
    possession: "any",
  })
  async connectAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        connect: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/aiModel")
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "update",
    possession: "any",
  })
  async updateAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        set: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/aiModel")
  @nestAccessControl.UseRoles({
    resource: "Annotation",
    action: "update",
    possession: "any",
  })
  async disconnectAiModel(
    @common.Param() params: AnnotationWhereUniqueInput,
    @common.Body() body: AimodelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiModel: {
        disconnect: body,
      },
    };
    await this.service.updateAnnotation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
