/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Annotation as PrismaAnnotation,
  Aimodel as PrismaAimodel,
  Image as PrismaImage,
  User as PrismaUser,
} from "@prisma/client";

export class AnnotationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AnnotationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.annotation.count(args);
  }

  async annotations(
    args: Prisma.AnnotationFindManyArgs
  ): Promise<PrismaAnnotation[]> {
    return this.prisma.annotation.findMany(args);
  }
  async annotation(
    args: Prisma.AnnotationFindUniqueArgs
  ): Promise<PrismaAnnotation | null> {
    return this.prisma.annotation.findUnique(args);
  }
  async createAnnotation(
    args: Prisma.AnnotationCreateArgs
  ): Promise<PrismaAnnotation> {
    return this.prisma.annotation.create(args);
  }
  async updateAnnotation(
    args: Prisma.AnnotationUpdateArgs
  ): Promise<PrismaAnnotation> {
    return this.prisma.annotation.update(args);
  }
  async deleteAnnotation(
    args: Prisma.AnnotationDeleteArgs
  ): Promise<PrismaAnnotation> {
    return this.prisma.annotation.delete(args);
  }

  async findAiModel(
    parentId: string,
    args: Prisma.AimodelFindManyArgs
  ): Promise<PrismaAimodel[]> {
    return this.prisma.annotation
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .aiModel(args);
  }

  async getImage(parentId: string): Promise<PrismaImage | null> {
    return this.prisma.annotation
      .findUnique({
        where: { id: parentId },
      })
      .image();
  }

  async getValidatedBy(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.annotation
      .findUnique({
        where: { id: parentId },
      })
      .validatedBy();
  }
}
