/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Annotation } from "./Annotation";
import { AnnotationCountArgs } from "./AnnotationCountArgs";
import { AnnotationFindManyArgs } from "./AnnotationFindManyArgs";
import { AnnotationFindUniqueArgs } from "./AnnotationFindUniqueArgs";
import { CreateAnnotationArgs } from "./CreateAnnotationArgs";
import { UpdateAnnotationArgs } from "./UpdateAnnotationArgs";
import { DeleteAnnotationArgs } from "./DeleteAnnotationArgs";
import { AimodelFindManyArgs } from "../../aimodel/base/AimodelFindManyArgs";
import { Aimodel } from "../../aimodel/base/Aimodel";
import { Image } from "../../image/base/Image";
import { User } from "../../user/base/User";
import { AnnotationService } from "../annotation.service";
@graphql.Resolver(() => Annotation)
export class AnnotationResolverBase {
  constructor(protected readonly service: AnnotationService) {}

  async _annotationsMeta(
    @graphql.Args() args: AnnotationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Annotation])
  async annotations(
    @graphql.Args() args: AnnotationFindManyArgs
  ): Promise<Annotation[]> {
    return this.service.annotations(args);
  }

  @graphql.Query(() => Annotation, { nullable: true })
  async annotation(
    @graphql.Args() args: AnnotationFindUniqueArgs
  ): Promise<Annotation | null> {
    const result = await this.service.annotation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Annotation)
  async createAnnotation(
    @graphql.Args() args: CreateAnnotationArgs
  ): Promise<Annotation> {
    return await this.service.createAnnotation({
      ...args,
      data: {
        ...args.data,

        image: {
          connect: args.data.image,
        },

        validatedBy: args.data.validatedBy
          ? {
              connect: args.data.validatedBy,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Annotation)
  async updateAnnotation(
    @graphql.Args() args: UpdateAnnotationArgs
  ): Promise<Annotation | null> {
    try {
      return await this.service.updateAnnotation({
        ...args,
        data: {
          ...args.data,

          image: {
            connect: args.data.image,
          },

          validatedBy: args.data.validatedBy
            ? {
                connect: args.data.validatedBy,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Annotation)
  async deleteAnnotation(
    @graphql.Args() args: DeleteAnnotationArgs
  ): Promise<Annotation | null> {
    try {
      return await this.service.deleteAnnotation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Aimodel], { name: "aiModel" })
  async findAiModel(
    @graphql.Parent() parent: Annotation,
    @graphql.Args() args: AimodelFindManyArgs
  ): Promise<Aimodel[]> {
    const results = await this.service.findAiModel(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Image, {
    nullable: true,
    name: "image",
  })
  async getImage(@graphql.Parent() parent: Annotation): Promise<Image | null> {
    const result = await this.service.getImage(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "validatedBy",
  })
  async getValidatedBy(
    @graphql.Parent() parent: Annotation
  ): Promise<User | null> {
    const result = await this.service.getValidatedBy(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
