/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AppConfig } from "./AppConfig";
import { AppConfigCountArgs } from "./AppConfigCountArgs";
import { AppConfigFindManyArgs } from "./AppConfigFindManyArgs";
import { AppConfigFindUniqueArgs } from "./AppConfigFindUniqueArgs";
import { CreateAppConfigArgs } from "./CreateAppConfigArgs";
import { UpdateAppConfigArgs } from "./UpdateAppConfigArgs";
import { DeleteAppConfigArgs } from "./DeleteAppConfigArgs";
import { AppConfigService } from "../appConfig.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AppConfig)
export class AppConfigResolverBase {
  constructor(
    protected readonly service: AppConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "read",
    possession: "any",
  })
  async _appConfigsMeta(
    @graphql.Args() args: AppConfigCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AppConfig])
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "read",
    possession: "any",
  })
  async appConfigs(
    @graphql.Args() args: AppConfigFindManyArgs
  ): Promise<AppConfig[]> {
    return this.service.appConfigs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AppConfig, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "read",
    possession: "own",
  })
  async appConfig(
    @graphql.Args() args: AppConfigFindUniqueArgs
  ): Promise<AppConfig | null> {
    const result = await this.service.appConfig(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AppConfig)
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "create",
    possession: "any",
  })
  async createAppConfig(
    @graphql.Args() args: CreateAppConfigArgs
  ): Promise<AppConfig> {
    return await this.service.createAppConfig({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AppConfig)
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "update",
    possession: "any",
  })
  async updateAppConfig(
    @graphql.Args() args: UpdateAppConfigArgs
  ): Promise<AppConfig | null> {
    try {
      return await this.service.updateAppConfig({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AppConfig)
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "delete",
    possession: "any",
  })
  async deleteAppConfig(
    @graphql.Args() args: DeleteAppConfigArgs
  ): Promise<AppConfig | null> {
    try {
      return await this.service.deleteAppConfig(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
