/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AppConfigService } from "../appConfig.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AppConfigCreateInput } from "./AppConfigCreateInput";
import { AppConfig } from "./AppConfig";
import { AppConfigFindManyArgs } from "./AppConfigFindManyArgs";
import { AppConfigWhereUniqueInput } from "./AppConfigWhereUniqueInput";
import { AppConfigUpdateInput } from "./AppConfigUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AppConfigControllerBase {
  constructor(
    protected readonly service: AppConfigService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppConfig })
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAppConfig(
    @common.Body() data: AppConfigCreateInput
  ): Promise<AppConfig> {
    return await this.service.createAppConfig({
      data: data,
      select: {
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AppConfig] })
  @ApiNestedQuery(AppConfigFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appConfigs(@common.Req() request: Request): Promise<AppConfig[]> {
    const args = plainToClass(AppConfigFindManyArgs, request.query);
    return this.service.appConfigs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appConfig(
    @common.Param() params: AppConfigWhereUniqueInput
  ): Promise<AppConfig | null> {
    const result = await this.service.appConfig({
      where: params,
      select: {
        createdAt: true,
        id: true,
        key: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAppConfig(
    @common.Param() params: AppConfigWhereUniqueInput,
    @common.Body() data: AppConfigUpdateInput
  ): Promise<AppConfig | null> {
    try {
      return await this.service.updateAppConfig({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          key: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppConfig })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppConfig",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAppConfig(
    @common.Param() params: AppConfigWhereUniqueInput
  ): Promise<AppConfig | null> {
    try {
      return await this.service.deleteAppConfig({
        where: params,
        select: {
          createdAt: true,
          id: true,
          key: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
