/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AppConfig as PrismaAppConfig } from "@prisma/client";

export class AppConfigServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AppConfigCountArgs, "select">
  ): Promise<number> {
    return this.prisma.appConfig.count(args);
  }

  async appConfigs(
    args: Prisma.AppConfigFindManyArgs
  ): Promise<PrismaAppConfig[]> {
    return this.prisma.appConfig.findMany(args);
  }
  async appConfig(
    args: Prisma.AppConfigFindUniqueArgs
  ): Promise<PrismaAppConfig | null> {
    return this.prisma.appConfig.findUnique(args);
  }
  async createAppConfig(
    args: Prisma.AppConfigCreateArgs
  ): Promise<PrismaAppConfig> {
    return this.prisma.appConfig.create(args);
  }
  async updateAppConfig(
    args: Prisma.AppConfigUpdateArgs
  ): Promise<PrismaAppConfig> {
    return this.prisma.appConfig.update(args);
  }
  async deleteAppConfig(
    args: Prisma.AppConfigDeleteArgs
  ): Promise<PrismaAppConfig> {
    return this.prisma.appConfig.delete(args);
  }
}
