/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthModel } from "./AuthModel";
import { AuthModelCountArgs } from "./AuthModelCountArgs";
import { AuthModelFindManyArgs } from "./AuthModelFindManyArgs";
import { AuthModelFindUniqueArgs } from "./AuthModelFindUniqueArgs";
import { DeleteAuthModelArgs } from "./DeleteAuthModelArgs";
import { AuthModelService } from "../authModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AuthModel)
export class AuthModelResolverBase {
  constructor(
    protected readonly service: AuthModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AuthModel",
    action: "read",
    possession: "any",
  })
  async _authModelsMeta(
    @graphql.Args() args: AuthModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AuthModel])
  @nestAccessControl.UseRoles({
    resource: "AuthModel",
    action: "read",
    possession: "any",
  })
  async authModels(
    @graphql.Args() args: AuthModelFindManyArgs
  ): Promise<AuthModel[]> {
    return this.service.authModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AuthModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AuthModel",
    action: "read",
    possession: "own",
  })
  async authModel(
    @graphql.Args() args: AuthModelFindUniqueArgs
  ): Promise<AuthModel | null> {
    const result = await this.service.authModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AuthModel)
  @nestAccessControl.UseRoles({
    resource: "AuthModel",
    action: "delete",
    possession: "any",
  })
  async deleteAuthModel(
    @graphql.Args() args: DeleteAuthModelArgs
  ): Promise<AuthModel | null> {
    try {
      return await this.service.deleteAuthModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
