/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AuthModel as PrismaAuthModel } from "@prisma/client";

export class AuthModelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AuthModelCountArgs, "select">
  ): Promise<number> {
    return this.prisma.authModel.count(args);
  }

  async authModels(
    args: Prisma.AuthModelFindManyArgs
  ): Promise<PrismaAuthModel[]> {
    return this.prisma.authModel.findMany(args);
  }
  async authModel(
    args: Prisma.AuthModelFindUniqueArgs
  ): Promise<PrismaAuthModel | null> {
    return this.prisma.authModel.findUnique(args);
  }
  async createAuthModel(
    args: Prisma.AuthModelCreateArgs
  ): Promise<PrismaAuthModel> {
    return this.prisma.authModel.create(args);
  }
  async updateAuthModel(
    args: Prisma.AuthModelUpdateArgs
  ): Promise<PrismaAuthModel> {
    return this.prisma.authModel.update(args);
  }
  async deleteAuthModel(
    args: Prisma.AuthModelDeleteArgs
  ): Promise<PrismaAuthModel> {
    return this.prisma.authModel.delete(args);
  }
}
